### ISSUE TITLE
1.14-pre5 failed to load

### ISSUE THREAD

**Issue by Explorare** [bangbang93/BMCL#42]
Minecraft 1.14-pre5

### Crash Report
04/20/2019 17:42:25崩溃:---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/21/19 11:14 PM
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at cqz.b(SourceFile:206)
	at cqp.c(SourceFile:38)
	at cqp.a(SourceFile:27)
	at csl$a.<init>(SourceFile:56)
	at csl.<init>(SourceFile:23)
	at cvo.c(SourceFile:61)
	at cvi.a(SourceFile:312)
	at cqw.a(SourceFile:829)
	at cvb$9.a(SourceFile:99)
	at crz.a(SourceFile:153)
	at csu.a(SourceFile:22)
	at cqx.b(SourceFile:86)
	at cvi.a(SourceFile:430)
	at cqx.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at cpo.l(SourceFile:422)
	at cpo.c(SourceFile:280)
	at cqw.b_(SourceFile:1022)
	at cqw.d(SourceFile:975)
	at cqw.b(SourceFile:412)
	at net.minecraft.client.main.Main.main(SourceFile:154)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cqz.b(SourceFile:206)
	at cqp.c(SourceFile:38)
	at cqp.a(SourceFile:27)
	at csl$a.<init>(SourceFile:56)
	at csl.<init>(SourceFile:23)
	at cvo.c(SourceFile:61)
	at cvi.a(SourceFile:312)
	at cqw.a(SourceFile:829)
	at cvb$9.a(SourceFile:99)
	at crz.a(SourceFile:153)
	at csu.a(SourceFile:22)
	at cqx.b(SourceFile:86)

-- Affected screen --
Details:
	Screen name: cvb
Stacktrace:
	at cvi.a(SourceFile:430)
	at cqx.a(SourceFile:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at cpo.l(SourceFile:422)
	at cpo.c(SourceFile:280)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [dft['explorare'/3250, l='MpServer', x=68.43, y=51.00, z=-179.34]]
	Chunk stats: MultiplayerChunkCache: 625, 481
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (192,64,-19), Chunk: (at 0,4,13 in 12,-2; contains blocks 192,0,-32 to 207,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 110921 game time, 110921 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at ddi.a(SourceFile:449)
	at cqw.b(SourceFile:1919)
	at cqw.b(SourceFile:420)
	at net.minecraft.client.main.Main.main(SourceFile:154)

-- System Details --
Details:
	Minecraft Version: 19w08a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 561822872 bytes (535 MB) / 1123024896 bytes (1071 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2048M
	Launched Version: 19w08a
	LWJGL: 3.2.1 build 12
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6472, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by xfl03** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/5419
It may due to Minecraft itself, 1.13.2 also has this issue.

**Comment by Explorare** [comment]
But the official launcher works well with this version.

**Comment by xfl03** [comment]
How about 1.14 release?

**Comment by Explorare** [comment]
The 1.14 stable release works well without problem.
