### ISSUE TITLE
Lack of support for vanilla mods?

### ISSUE THREAD

**Issue by Explorare** [bangbang93/BMCL#43]
**Issue**
No java process was created launching using BMCL. As is discussed in this issue https://github.com/sp614x/optifine/issues/2644 ,the new version of OptiFine is now a vanilla, and no JAR file is needed anymore. So will BMCL support this kind of mods in the near future?

Thanks

**Logs**
```
[16:29:55] [main/INFO]: Initialized cache system in 65834700 ns
[16:29:55] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[16:29:55] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[16:29:55] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[16:29:55] [main/ERROR]: Unable to launch
java.lang.NullPointerException: null
	at optifine.OptiFineTweaker.acceptOptions(OptiFineTweaker.java:29) ~[OptiFine-1.14.3_HD_U_F1.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:136) [launchwrapper-2.0.jar:2.0.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23) [launchwrapper-2.0.jar:2.0.2]
```

**Environment**
System: Windows 10 1903
Java: 1.8.0_221
Minecraft: 1.14.3
OptiFine: 1.14.3_HD_U_F1
BMCL: 4.8

**Comment by xfl03** [comment]
I can make it support, if @bangbang93 think it should be done.

**Comment by bangbang93** [comment]
> I can make it support, if @bangbang93 think it should be done.

Sure. I haven’t played Minecraft for a while. And I have no idea with what happened to Minecraft ecosystem recently.

**Comment by xfl03** [comment]
I'm sorry about it, but I don't have enough disk space to install Visual Studio :(
